---
title: "Goldin (2014)"
author: 'Group4'
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_float: yes
    theme: flatly
  pdf_document:
    toc: yes
---

```{r load package, include=FALSE}

knitr::opts_chunk$set(echo = TRUE,message = FALSE, warning = FALSE)

library(tidyverse)

```

```{r load data}
# 回帰分析の結果を読み込む

result_0406 <- read_rds(here::here("Fig1", "data", "cleaned", "0406_result.rds"))
result_0911 <- read_rds(here::here("Fig1", "data", "cleaned", "0911_result.rds"))
result_1970 <- read_rds(here::here("Fig1", "data", "cleaned", "1970_result.rds"))
result_1980 <- read_rds(here::here("Fig1", "data", "cleaned", "1980_result.rds"))
result_1990 <- read_rds(here::here("Fig1", "data", "cleaned", "1990_result.rds"))
result_2000 <- read_rds(here::here("Fig1", "data", "cleaned", "2000_result.rds"))
```


```{r}
#回帰結果のリストを作る

result_list <- list(result_1970, result_1980, result_1990, result_2000, result_0406,  result_0911)
```

```{r}
#関数作成
function_1 <- function(model){
  coefs <- coef(model)
  
  female <- coefs["d_female"]
  
  ages <- coefs[paste0("f_age", 2:9)]
  
  fages <- female + ages
  
  a <- append(female, fages)
  
  return(a)
  
  }
  
```



```{r}
#各リストに対してfunction_1を実行し、データフレームにする
results <- map_dfr(result_list, function_1) |>
  rename(f_age1 = d_female)  #1列目の名前を他とそろえる
```

```{r}
results
```

```{r}

# 仮に df が 6x9 の tibble
# 調査年を別ベクトルで用意
survey_years <- c(1970, 1980, 1990, 2000, 2005, 2010)

df_long <- results %>%
  mutate(survey_year = survey_years) %>%
  pivot_longer(
    cols = starts_with("f_age"),
    names_to = "age_group",
    values_to = "wage_gap"
  ) %>%
  mutate(
    # f_age1 = 25-30歳, f_age2 = 31-35歳 ... みたいにルールを自分で決める
    age = case_when(
      age_group == "f_age1" ~ 27, # 中心値を使う
      age_group == "f_age2" ~ 32,
      age_group == "f_age3" ~ 37,
      age_group == "f_age4" ~ 42,
      age_group == "f_age5" ~ 47,
      age_group == "f_age6" ~ 52,
      age_group == "f_age7" ~ 57,
      age_group == "f_age8" ~ 62,
      age_group == "f_age9" ~ 67
    ),
    birth_year = survey_year - age
  )
```
```{r}
df_long_f <- df_long %>%
  filter(birth_year >= 1920, birth_year <= 1980)

```

```{r}
# グラフ1
G1 <- ggplot(df_long_f, aes(x = age, y = wage_gap, color = factor(birth_year), group = birth_year)) +
  geom_line(size=1) +
  geom_point() +
  labs(
    x = "年齢",
    y = "男女賃金差",
    color = "出生年"
  ) +
  theme_minimal()
G1
```
```{r}
df_long_f2 <- df_long_f |>
  filter(birth_year %in% c(1943, 1953, 1963, 1973) & age_group == "f_age1")
```

```{r}
d1 <- c(0,0,0)
d2 <- c(0,0,0)
wage1 <- c((df_long_f2[1, 3] + df_long_f2[2, 3])/2, 27, 1948)
age1 <- c((df_long_f2[1, 3] + df_long_f2[2, 3])/2, 37, 1938)
birth1 <- c((df_long_f2[1, 3] + df_long_f2[2, 3])/2, 47, 1928)

data2 <- data.frame(d1, d2, wage1, age1, birth1)

```
```{r}
data2
```
```{r}
data2[,3 ,5]
```




```{r}

#グラフ2
G2 <- ggplot(df_long_f, aes(x = age, y = wage_gap, color = factor(birth_year), group = birth_year)) +
  geom_line(size=1) +
  geom_point() +
  labs(
    x = "年齢",
    y = "男女賃金差",
    color = "出生年"
  ) +
  theme_minimal()
G2
```


# 課題の内容


# 取り組んだ手順
1. データリストを読み込み、一つのリスト（result_list)の中に格納しました。
2. 係数から男女の賃金差を計算する関数（function_1）を作成し、1.で作成したリスト（result_list）内の各リストに対して実行しました。実行した結果をデータフレーム（results）として保存しました。
3. 

# レプリケーション結果

以下にグラフを作成するコードを記入してください。

適宜チャンクを分けてください。
```{r}
pacman::p_load(tidyverse, foreign, haven, estimatr, fixest, here)
```

```{r}

```




# 結果の解釈

ここに結果の解釈を記入してください。



































