quietly label variable          returned_5             "if returned 5 year survey                     "
quietly label variable          returned_15            "if returned 15 year survey                    "
quietly label variable          returned_25            "if returned 25 year survey                    "
quietly label variable          jdyr                   "year of JD                                    "
quietly label variable          cohort                 "cohort year in 5 year intervals               "
quietly label variable          cohort70               "jdyr 1970-74                                  "
quietly label variable          cohort75               "jdyr 1975-79                                  "
quietly label variable          cohort80               "jdyr 1980-84                                  "
quietly label variable          cohort85               "jdyr 1985-89                                  "
quietly label variable          cohort90               "jdyr 1990-94                                  "
quietly label variable          cohort95               "jdyr 1995-99                                  "
quietly label variable          decade                 "graduation decade                             "
quietly label variable          group_15               "if individual is in 15 year survey            "
quietly label variable          group_5                "if individual is in 5 year survey             "
quietly label variable          female                 "female                                        "
quietly label variable          race                   "race                                          "
quietly label variable          black                  "race = black                                  "
quietly label variable          hispanic               "race = hispanic                               "
quietly label variable          asian                  "race = asian                                  "
quietly label variable          other                  "race = other (includes missing)               "
quietly label variable          white                  "race = white                                  "
quietly label variable          birthyear              "birth year                                    "
quietly label variable          yearba                 "year of BA                                    "
quietly label variable          yearlsentry            "year of law school entry                      "
quietly label variable          yearlsgrad             "year of law school graduation                 "
quietly label variable          yearsinls              "years in law school                           "
quietly label variable          timeoff                "time between BA and law school entry          "
quietly label variable          surveyyear_5           "year of 5 year survey                         "
quietly label variable          surveyyear_15          "year of 15 year survey                        "
quietly label variable          surveyyear_25          "year of 25 year survey                        "
quietly label variable          ageatba                "age at BA graduation                          "
quietly label variable          ageatlsentry           "age at law school entry                       "
quietly label variable          ageatlsgrad            "age at law school graduation                  "
quietly label variable          ageatlsgrad_2          "square of age at ls grad                      "
quietly label variable          age_5                  "age at 5 year survey                          "
quietly label variable          age_5_2                "square of age at 5 year survey                "
quietly label variable          age_15                 "age at 15 year survey                         "
quietly label variable          age_15_2               "square of age at 15 year survey               "
quietly label variable          age_25                 "age at 25 year survey                         "
quietly label variable          age_25_2               "square of age at 25 year survey               "
quietly label variable          parresregion           "parent's region                               "
quietly label variable          motherocc              "mother's occcode                              "
quietly label variable          fatherocc              "father's occcode                              "
quietly label variable          marstatprels           "marital status before law school              "
quietly label variable          marstatlsgrad          "marital status at law school graduation       "
quietly label variable          marriedprels           "if married before law school                  "
quietly label variable          marriedlsgrad          "if married at law school graduation           "
quietly label variable          spouseocc_5            "spouse occcode at year 5                      "
quietly label variable          spouseprof_5           "spouse has professional occup                 "
quietly label variable          spouseocc_15           "spouse occcode at year 15                     "
quietly label variable          spouseprof_15          "spouse has professional occup                 "
quietly label variable          spouseocc_25           "spouse occcode at year 25                     "
quietly label variable          spouseprof_25          "spouse has professional occup                 "
quietly label variable          spouseincadj_5         "spouse adj income year 5                      "
quietly label variable          logspouseinc~_5        "log spouse adj income                         "
quietly label variable          spouseincadj_15        "spouse adj income year 15                     "
quietly label variable          logspouseinc~15        "log spouse adj income                         "
quietly label variable          spouseincadj_25        "spouse adj income year 25                     "
quietly label variable          logspouseinc~25        "log spouse adj income                         "
quietly label variable          marstat_5              "marstat at year                               "
quietly label variable          married_5              "married at year                               "
quietly label variable          evermarried_5          "evermarried at year                           "
quietly label variable          marstat_15             "marstat at year                               "
quietly label variable          married_15             "married at year                               "
quietly label variable          evermarried_15         "evermarried at year                           "
quietly label variable          marstat_25             "marstat at year                               "
quietly label variable          married_25             "married at year                               "
quietly label variable          evermarried_25         "evermarried at year                           "
quietly label variable          zeroinc_5              "indicator for spouse has no income            "
quietly label variable          zeroinc_15             "indicator for spouse has no income            "
quietly label variable          zeroinc_25             "indicator for spouse has no income            "
quietly label variable          cohabit_5              "cohabit                                       "
quietly label variable          cohabit_15             "cohabit                                       "
quietly label variable          cohabit_25             "cohabit                                       "
quietly label variable          partnered_5            "partnered                                     "
quietly label variable          partnered_15           "partnered                                     "
quietly label variable          partnered_25           "partnered                                     "
quietly label variable          spousebin_5            "spousebin                                     "
quietly label variable          spousebin_15           "spousebin                                     "
quietly label variable          spousebin_25           "spousebin                                     "
quietly label variable          numchprels             "kids pre ls                                   "
quietly label variable          chprels                "# children pre ls                             "
quietly label variable          numchlsgrad            "kids @ grad                                   "
quietly label variable          chlsgrad               "# children @ grad                             "
quietly label variable          numch_5                "number of children                            "
quietly label variable          ch_5                   "if children                                   "
quietly label variable          ch06_5                 "if children < 6                               "
quietly label variable          chcarecost_5           "child care costs                              "
quietly label variable          missingchcar~_5        "missing child care cost                       "
quietly label variable          numch_15               "number of children                            "
quietly label variable          ch_15                  "if children                                   "
quietly label variable          ch06_15                "if children < 6                               "
quietly label variable          chcarecost_15          "child care costs                              "
quietly label variable          missingchcar~15        "missing child care cost                       "
quietly label variable          numch_25               "number of children                            "
quietly label variable          ch_25                  "if children                                   "
quietly label variable          ch06_25                "if children < 6                               "
quietly label variable          chcarecost_25          "child care costs                              "
quietly label variable          missingchcar~25        "missing child care cost                       "
quietly label variable          uggpa                  "undergraduate gpa                             "
quietly label variable          lsatperc               "lsat                                          "
quietly label variable          missingprels           "missing information on pre-ls                 "
quietly label variable          ugschool               "undergrad school                              "
quietly label variable          ivy7                   "ivy or 7 sisters                              "
quietly label variable          ugmajor                "ugmajor                                       "
quietly label variable          popcitywork_5          "population work city                          "
quietly label variable          popcitywork_15         "population work city                          "
quietly label variable          popcitywork_25         "population work city                          "
quietly label variable          region_5               "region                                        "
quietly label variable          region_15              "region                                        "
quietly label variable          region_25              "region                                        "
quietly label variable          graddegree             "graddegree                                    "
quietly label variable          graddegfield           "graddegfield                                  "
quietly label variable          planprels              "careerplan pre ls                             "
quietly label variable          planlsgrad             "careerplan at ls grad                         "
quietly label variable          specplanned_5          "specplanned                                   "
quietly label variable          specplanned_15         "specplanned                                   "
quietly label variable          specplanned_25         "specplanned                                   "
quietly label variable          legalsociety           "legal society                                 "
quietly label variable          mootcourt              "moot court                                    "
quietly label variable          lawreview              "law review                                    "
quietly label variable          studentgovt            "student gov't                                 "
quietly label variable          lsgpayr1               "ls gpa first year                             "
quietly label variable          missinglsyr1           "missing information on ls first year          "
quietly label variable          transfer               "transfer student                              "
quietly label variable          lsgpa                  "final gpa                                     "
quietly label variable          lscoldebt              "total schooling debt                          "
quietly label variable          orgtype_5              "job org type                                  "
quietly label variable          postype_5              "job post type                                 "
quietly label variable          lawyer_5               "is a lawyer                                   "
quietly label variable          attystatus_5           "attystatus                                    "
quietly label variable          wksetting_5            "consolidated                                  "
quietly label variable          nonpsetting_5          "nonpractice                                   "
quietly label variable          orgtype_15             "orgtype                                       "
quietly label variable          postype_15             "postype                                       "
quietly label variable          lawyer_15              "is a lawyer                                   "
quietly label variable          attystatus_15          "attystatus                                    "
quietly label variable          wksetting_15           "consolidated                                  "
quietly label variable          nonpsetting_15         "nonpractice                                   "
quietly label variable          orgtype_25             "orgtype                                       "
quietly label variable          postype_25             "postype                                       "
quietly label variable          lawyer_25              "is a lawyer                                   "
quietly label variable          attystatus_25          "attystatus                                    "
quietly label variable          wksetting_25           "consolidated                                  "
quietly label variable          nonpsetting_25         "nonpractice                                   "
quietly label variable          clerk                  "ever a clerk                                  "
quietly label variable          firstjob               "firstjob                                      "
quietly label variable          numlawfirstjob         "number of lawers at first job                 "
quietly label variable          yrspt_5                "years part time                               "
quietly label variable          yrsnotemp_5            "years not working                             "
quietly label variable          missingpt_5            "                                              "
quietly label variable          missingnotemp_5        "                                              "
quietly label variable          yrspt_5_2              "years part time ^2                            "
quietly label variable          yrsnotemp_5_2          "years not working ^2                          "
quietly label variable          everpt_5               "ever part time                                "
quietly label variable          evernotemp_5           "                                              "
quietly label variable          yrspt_15               "years part time                               "
quietly label variable          yrsnotemp_15           "years not working                             "
quietly label variable          missingpt_15           "                                              "
quietly label variable          missingnotem~15        "                                              "
quietly label variable          yrspt_15_2             "years part time ^2                            "
quietly label variable          yrsnotemp_15_2         "                                              "
quietly label variable          everpt_15              "ever part time                                "
quietly label variable          evernotemp_15          "                                              "
quietly label variable          yrspt_25               "years part time                               "
quietly label variable          yrsnotemp_25           "years not working                             "
quietly label variable          missingpt_25           "                                              "
quietly label variable          missingnotem~25        "                                              "
quietly label variable          yrspt_25_2             "years part time ^2                            "
quietly label variable          yrsnotemp_25_2         "years not working ^2                          "
quietly label variable          everpt_25              "ever part time                                "
quietly label variable          evernotemp_25          "                                              "
quietly label variable          exp_ft_5               "full time experience                          "
quietly label variable          missingexp_ft_5        "                                              "
quietly label variable          exp_ft_5_2             "                                              "
quietly label variable          exp_5                  " all experience (pt and ft)                   "
quietly label variable          missingexp_5           "                                              "
quietly label variable          exp_5_2                "                                              "
quietly label variable          exp_ft_15              "full time experience                          "
quietly label variable          missingexp_f~15        "                                              "
quietly label variable          exp_ft_15_2            "                                              "
quietly label variable          exp_15                 "all experience (pt and ft)                    "
quietly label variable          missingexp_15          "                                              "
quietly label variable          exp_15_2               "                                              "
quietly label variable          exp_ft_25              "full time experience                          "
quietly label variable          missingexp_f~25        "                                              "
quietly label variable          exp_ft_25_2            "                                              "
quietly label variable          exp_25                 "all experience (pt and ft)                    "
quietly label variable          missingexp_25          "                                              "
quietly label variable          exp_25_2               "                                              "
quietly label variable          numjobs_5              "number of jobs                                "
quietly label variable          yrscurrjob_5           "years current job                             "
quietly label variable          yrsfirstjob_5          "years first job                               "
quietly label variable          yrsgovt_5              "years in govt                                 "
quietly label variable          yrslegserv_5           "years in legal service                        "
quietly label variable          yrsprac_5              "years in practice                             "
quietly label variable          yrspubint_5            "years in public interest law                  "
quietly label variable          missingyrscu~_5        "                                              "
quietly label variable          missingyrsfi~_5        "                                              "
quietly label variable          missingyrsgo~_5        "                                              "
quietly label variable          missingyrsle~_5        "                                              "
quietly label variable          missingyrspr~_5        "                                              "
quietly label variable          missingyrspu~_5        "                                              "
quietly label variable          numjobs_15             "number of jobs                                "
quietly label variable          yrscurrjob_15          "years current job                             "
quietly label variable          yrsfirstjob_15         "years first job                               "
quietly label variable          yrsgovt_15             "years in govt                                 "
quietly label variable          yrslegserv_15          "years in legal service                        "
quietly label variable          yrsprac_15             "years in practice                             "
quietly label variable          yrspubint_15           "years in public interest law                  "
quietly label variable          missingyrscu~15        "                                              "
quietly label variable          missingyrsfi~15        "                                              "
quietly label variable          missingyrsgo~15        "                                              "
quietly label variable          missingyrsle~15        "                                              "
quietly label variable          missingyrspr~15        "                                              "
quietly label variable          missingyrspu~15        "                                              "
quietly label variable          numjobs_25             "number of jobs                                "
quietly label variable          yrscurrjob_25          "years current job                             "
quietly label variable          yrsfirstjob_25         "years first job                               "
quietly label variable          yrsgovt_25             "years in govt                                 "
quietly label variable          yrslegserv_25          "years in legal service                        "
quietly label variable          yrsprac_25             "years in practice                             "
quietly label variable          yrspubint_25           "years in public interest law                  "
quietly label variable          missingyrscu~25        "                                              "
quietly label variable          missingyrsfi~25        "                                              "
quietly label variable          missingyrsgo~25        "                                              "
quietly label variable          missingyrsle~25        "                                              "
quietly label variable          missingyrspr~25        "                                              "
quietly label variable          missingyrspu~25        "                                              "
quietly label variable          empstat_5              "employment status                             "
quietly label variable          hrsperyr_5             "hours per year                                "
quietly label variable          hrsperwk_5             "hours per week                                "
quietly label variable          wksperyr_5             "weeks per year                                "
quietly label variable          missingwksyr_5         "                                              "
quietly label variable          missinghours~_5        "                                              "
quietly label variable          hrsbin_5               "hours bin                                     "
quietly label variable          notempnow_5            "not in labor force                            "
quietly label variable          ptnow_5                "                                              "
quietly label variable          loghourswk_5           "log hours per week                            "
quietly label variable          logwksyr_5             "log weeks per year                            "
quietly label variable          empstat_15             "employment status                             "
quietly label variable          hrsperyr_15            "hours per year                                "
quietly label variable          hrsperwk_15            "hours per week                                "
quietly label variable          wksperyr_15            "weeks per year                                "
quietly label variable          missingwksyr_15        "                                              "
quietly label variable          missinghours~15        "                                              "
quietly label variable          hrsbin_15              "hours bin                                     "
quietly label variable          notempnow_15           "not in labor force                            "
quietly label variable          ptnow_15               "                                              "
quietly label variable          loghourswk_15          "log hours per week                            "
quietly label variable          logwksyr_15            "log weeks per year                            "
quietly label variable          empstat_25             "employment status                             "
quietly label variable          hrsperyr_25            "hours per year                                "
quietly label variable          hrsperwk_25            "hours per week                                "
quietly label variable          wksperyr_25            "weeks per year                                "
quietly label variable          missingwksyr_25        "                                              "
quietly label variable          missinghours~25        "                                              "
quietly label variable          hrsbin_25              "hours bin                                     "
quietly label variable          notempnow_25           "not in labor force                            "
quietly label variable          ptnow_25               "                                              "
quietly label variable          loghourswk_25          "log hours per week                            "
quietly label variable          logwksyr_25            "log weeks per year                            "
quietly label variable          samesetting_5          "anticipate moving jobs in 5 yrs               "
quietly label variable          reasonforlea~_5        "reason                                        "
quietly label variable          samesetting_15         "samesetting                                   "
quietly label variable          reasonforlea~15        "reason                                        "
quietly label variable          samesetting_25         "samesetting                                   "
quietly label variable          reasonforlea~25        "reason                                        "
quietly label variable          incadj_1               "income first year out in 2007 $               "
quietly label variable          logincadj_1            "log income first year out in 2007$            "
quietly label variable          missinginc1            "                                              "
quietly label variable          incadj_5               "adjusted income                               "
quietly label variable          incadj_15              "adjusted income                               "
quietly label variable          incadj_25              "adjusted income                               "
quietly label variable          logincadj_5            "log adjusted income                           "
quietly label variable          otherhhincadj_5        "other hh income adjusted                      "
quietly label variable          totalhhincadj_5        "total hh income adjusted                      "
quietly label variable          hourlyfee_5            "hourly fee                                    "
quietly label variable          logincadj_15           "log adjusted income                           "
quietly label variable          otherhhincad~15        "other hh income adjusted                      "
quietly label variable          totalhhincad~15        "total hh income adjusted                      "
quietly label variable          hourlyfee_15           "hourly fee                                    "
quietly label variable          logincadj_25           "log adjusted income                           "
quietly label variable          otherhhincad~25        "other hh income adjusted                      "
quietly label variable          totalhhincad~25        "total hh income adjusted                      "
quietly label variable          hourlyfee_25           "hourly fee                                    "
quietly label variable          educdebt_5             "educational debt                              "
quietly label variable          educdebt_15            "educational debt                              "
quietly label variable          educdebt_25            "educational debt                              "
quietly label variable          firmsize_5             "firm size                                     "
quietly label variable          logfirmsize_5          "log firm size                                 "
quietly label variable          solopractice_5         "solo practice                                 "
quietly label variable          missingfirms~_5        "                                              "
quietly label variable          numwomen_5             "number of women at the firm                   "
quietly label variable          numminorities_5        "number of minorities at the firm              "
quietly label variable          missingwomen_5         "                                              "
quietly label variable          missingminor_5         "                                              "
quietly label variable          fracwomen_5            "fraction of women                             "
quietly label variable          fracminor_5            "fraction of minorities                        "
quietly label variable          firmsizebin_5          "                                              "
quietly label variable          firmsize_15            "firm size                                     "
quietly label variable          logfirmsize_15         "log firm size                                 "
quietly label variable          solopractice_15        "solo practice                                 "
quietly label variable          missingfirms~15        "                                              "
quietly label variable          numwomen_15            "number of women at the firm                   "
quietly label variable          numminoritie~15        "number of minorities at the firm              "
quietly label variable          missingwomen_15        "                                              "
quietly label variable          missingminor_15        "                                              "
quietly label variable          fracwomen_15           "fraction of women                             "
quietly label variable          fracminor_15           "fraction of minorities                        "
quietly label variable          firmsizebin_15         "                                              "
quietly label variable          firmsize_25            "firm size                                     "
quietly label variable          logfirmsize_25         "log firm size                                 "
quietly label variable          solopractice_25        "solo practice                                 "
quietly label variable          missingfirms~25        "                                              "
quietly label variable          numwomen_25            "number of women at the firm                   "
quietly label variable          numminoritie~25        "number of minorities at the firm              "
quietly label variable          missingwomen_25        "                                              "
quietly label variable          missingminor_25        "                                              "
quietly label variable          fracwomen_25           "fraction of women                             "
quietly label variable          fracminor_25           "fraction of minorities                        "
quietly label variable          firmsizebin_25         "                                              "
quietly label variable          time_lib_5             "time: library                                 "
quietly label variable          time_int_5             "time: interview                               "
quietly label variable          time_lit_5             "time: litigation                              "
quietly label variable          time_neg_5             "time: negotion                                "
quietly label variable          time_draft_5           "time: drafting                                "
quietly label variable          time_app_5             "time: appeals                                 "
quietly label variable          time_lob_5             "time: lobbying                                "
quietly label variable          time_adm_5             "time: office admin                            "
quietly label variable          time_led_5             "time: legal ed                                "
quietly label variable          time_soc_5             "time: socializing with co-workers             "
quietly label variable          time_rec_5             "time: recruiting                              "
quietly label variable          time_oth_5             "time: other                                   "
quietly label variable          missingtime_5          "                                              "
quietly label variable          timeind_lib_5          "spend more than 10% of time on it             "
quietly label variable          timespec_lib_5         "spend more than 25% of time on it             "
quietly label variable          timesuper_lib_5        "spend more than 50% of time on it             "
quietly label variable          timeind_int_5          "spend more than 10% of time on it             "
quietly label variable          timespec_int_5         "spend more than 25% of time on it             "
quietly label variable          timesuper_int_5        "spend more than 50% of time on it             "
quietly label variable          timeind_lit_5          "spend more than 10% of time on it             "
quietly label variable          timespec_lit_5         "spend more than 25% of time on it             "
quietly label variable          timesuper_lit_5        "spend more than 50% of time on it             "
quietly label variable          timeind_neg_5          "spend more than 10% of time on it             "
quietly label variable          timespec_neg_5         "spend more than 25% of time on it             "
quietly label variable          timesuper_neg_5        "spend more than 50% of time on it             "
quietly label variable          timeind_draft_5        "spend more than 10% of time on it             "
quietly label variable          timespec_dra~_5        "spend more than 25% of time on it             "
quietly label variable          timesuper_dr~_5        "spend more than 50% of time on it             "
quietly label variable          timeind_app_5          "spend more than 10% of time on it             "
quietly label variable          timespec_app_5         "spend more than 25% of time on it             "
quietly label variable          timesuper_app_5        "spend more than 50% of time on it             "
quietly label variable          timeind_lob_5          "spend more than 10% of time on it             "
quietly label variable          timespec_lob_5         "spend more than 25% of time on it             "
quietly label variable          timesuper_lob_5        "spend more than 50% of time on it             "
quietly label variable          timeind_adm_5          "spend more than 10% of time on it             "
quietly label variable          timespec_adm_5         "spend more than 25% of time on it             "
quietly label variable          timesuper_adm_5        "spend more than 50% of time on it             "
quietly label variable          timeind_led_5          "spend more than 10% of time on it             "
quietly label variable          timespec_led_5         "spend more than 25% of time on it             "
quietly label variable          timesuper_led_5        "spend more than 50% of time on it             "
quietly label variable          timeind_soc_5          "spend more than 10% of time on it             "
quietly label variable          timespec_soc_5         "spend more than 25% of time on it             "
quietly label variable          timesuper_soc_5        "spend more than 50% of time on it             "
quietly label variable          timeind_rec_5          "spend more than 10% of time on it             "
quietly label variable          timespec_rec_5         "spend more than 25% of time on it             "
quietly label variable          timesuper_rec_5        "spend more than 50% of time on it             "
quietly label variable          timeind_oth_5          "spend more than 10% of time on it             "
quietly label variable          timespec_oth_5         "spend more than 25% of time on it             "
quietly label variable          timesuper_oth_5        "spend more than 50% of time on it             "
quietly label variable          herf_time_5            "Herfindahl index                              "
quietly label variable          time_lib_15            "time: library                                 "
quietly label variable          time_int_15            "time: interview                               "
quietly label variable          time_lit_15            "time: litigation                              "
quietly label variable          time_neg_15            "time: negotion                                "
quietly label variable          time_draft_15          "time: drafting                                "
quietly label variable          time_app_15            "time: apeals                                  "
quietly label variable          time_lob_15            "time: lobbying                                "
quietly label variable          time_adm_15            "time: office admin                            "
quietly label variable          time_led_15            "time: legal ed                                "
quietly label variable          time_soc_15            "time: socializing with co-workers             "
quietly label variable          time_rec_15            "time: recruiting                              "
quietly label variable          time_oth_15            "time: other                                   "
quietly label variable          missingtime_15         "                                              "
quietly label variable          timeind_lib_15         "                                              "
quietly label variable          timespec_lib_15        "                                              "
quietly label variable          timesuper~ib_15        "                                              "
quietly label variable          timeind_int_15         "                                              "
quietly label variable          timespec_int_15        "                                              "
quietly label variable          timesuper_in~15        "                                              "
quietly label variable          timeind_lit_15         "                                              "
quietly label variable          timespec_lit_15        "                                              "
quietly label variable          timesuper~it_15        "                                              "
quietly label variable          timeind_neg_15         "                                              "
quietly label variable          timespec_neg_15        "                                              "
quietly label variable          timesuper_ne~15        "                                              "
quietly label variable          timeind_draf~15        "                                              "
quietly label variable          timespec_dra~15        "                                              "
quietly label variable          timesuper_dr~15        "                                              "
quietly label variable          timeind_app_15         "                                              "
quietly label variable          timespec_app_15        "                                              "
quietly label variable          timesuper_ap~15        "                                              "
quietly label variable          timeind_lob_15         "                                              "
quietly label variable          timespec_lob_15        "                                              "
quietly label variable          timesuper_lo~15        "                                              "
quietly label variable          timeind_adm_15         "                                              "
quietly label variable          timespec_adm_15        "                                              "
quietly label variable          timesuper_ad~15        "                                              "
quietly label variable          timeind_led_15         "                                              "
quietly label variable          timespec_led_15        "                                              "
quietly label variable          timesuper_le~15        "                                              "
quietly label variable          timeind_soc_15         "                                              "
quietly label variable          timespec_soc_15        "                                              "
quietly label variable          timesuper_so~15        "                                              "
quietly label variable          timeind_rec_15         "                                              "
quietly label variable          timespec_rec_15        "                                              "
quietly label variable          timesuper_re~15        "                                              "
quietly label variable          timeind_oth_15         "                                              "
quietly label variable          timespec_oth_15        "                                              "
quietly label variable          timesuper_ot~15        "                                              "
quietly label variable          herf_time_15           "Herfindahl index                              "
quietly label variable          time_lib_25            "time: library                                 "
quietly label variable          time_int_25            "time: interview                               "
quietly label variable          time_lit_25            "time: litigation                              "
quietly label variable          time_neg_25            "time: negotion                                "
quietly label variable          time_draft_25          "time: drafting                                "
quietly label variable          time_app_25            "time: apeals                                  "
quietly label variable          time_lob_25            "time: lobbying                                "
quietly label variable          time_adm_25            "time: office admin                            "
quietly label variable          time_led_25            "time: legal ed                                "
quietly label variable          time_soc_25            "time: socializing with co-workers             "
quietly label variable          time_rec_25            "time: recruiting                              "
quietly label variable          time_oth_25            "time: other                                   "
quietly label variable          missingtime_25         "                                              "
quietly label variable          timeind_lib_25         "                                              "
quietly label variable          timespec_lib_25        "                                              "
quietly label variable          timesuper~ib_25        "                                              "
quietly label variable          timeind_int_25         "                                              "
quietly label variable          timespec_int_25        "                                              "
quietly label variable          timesuper_in~25        "                                              "
quietly label variable          timeind_lit_25         "                                              "
quietly label variable          timespec_lit_25        "                                              "
quietly label variable          timesuper~it_25        "                                              "
quietly label variable          timeind_neg_25         "                                              "
quietly label variable          timespec_neg_25        "                                              "
quietly label variable          timesuper_ne~25        "                                              "
quietly label variable          timeind_draf~25        "                                              "
quietly label variable          timespec_dra~25        "                                              "
quietly label variable          timesuper_dr~25        "                                              "
quietly label variable          timeind_app_25         "                                              "
quietly label variable          timespec_app_25        "                                              "
quietly label variable          timesuper_ap~25        "                                              "
quietly label variable          timeind_lob_25         "                                              "
quietly label variable          timespec_lob_25        "                                              "
quietly label variable          timesuper_lo~25        "                                              "
quietly label variable          timeind_adm_25         "                                              "
quietly label variable          timespec_adm_25        "                                              "
quietly label variable          timesuper_ad~25        "                                              "
quietly label variable          timeind_led_25         "                                              "
quietly label variable          timespec_led_25        "                                              "
quietly label variable          timesuper_le~25        "                                              "
quietly label variable          timeind_soc_25         "                                              "
quietly label variable          timespec_soc_25        "                                              "
quietly label variable          timesuper_so~25        "                                              "
quietly label variable          timeind_rec_25         "                                              "
quietly label variable          timespec_rec_25        "                                              "
quietly label variable          timesuper_re~25        "                                              "
quietly label variable          timeind_oth_25         "                                              "
quietly label variable          timespec_oth_25        "                                              "
quietly label variable          timesuper_ot~25        "                                              "
quietly label variable          herf_time_25           "Herfindahl index                              "
quietly label variable          subj_adm_5             "Subject: admin law                            "
quietly label variable          subj_anti_5            "Subject: antitrust                            "
quietly label variable          subj_bank_5            "Subject: banking                              "
quietly label variable          subj_bkrpt_5           "subject: bankruptcy                           "
quietly label variable          subj_civ_5             "subject: civil rights                         "
quietly label variable          subj_comm_5            "subjects: communication                       "
quietly label variable          subj_cmerc_5           "subject: commercial                           "
quietly label variable          subj_crim_5            "subject: criminal                             "
quietly label variable          subj_dom_5             "subject: domestic rl                          "
quietly label variable          subj_emp_5             "subject: employeeben                          "
quietly label variable          subj_ene_5             "subject: engergy                              "
quietly label variable          subj_env_5             "subject: environment                          "
quietly label variable          subj_est_5             "subject: estate plan                          "
quietly label variable          subj_govt_5            "subject: govt contractor                      "
quietly label variable          subj_imm_5             "subject: immigration                          "
quietly label variable          subj_tax_5             "subject: income tax                           "
quietly label variable          subj_ins_5             "subject insurance                             "
quietly label variable          subj_int_5             "subject: international                        "
quietly label variable          subj_lab_5             "subject: labor relations                      "
quietly label variable          subj_pat_5             "subject: patent/trademark                     "
quietly label variable          subj_real_5            "subject: real property                        "
quietly label variable          subj_sec_5             "subject: securities                           "
quietly label variable          subj_tort_5            "subject: tort                                 "
quietly label variable          subj_other_5           "subject: other                                "
quietly label variable          missingsubj_5          "                                              "
quietly label variable          subjind_adm_5          "spend more than 10% of time on it             "
quietly label variable          subjspec_adm_5         "spend more than 25% of time on it             "
quietly label variable          subjsuper_adm_5        "spend more than 50% of time on it             "
quietly label variable          subjind_anti_5         "                                              "
quietly label variable          subjspec_anti_5        "                                              "
quietly label variable          subjsuper_an~_5        "                                              "
quietly label variable          subjind_bank_5         "                                              "
quietly label variable          subjspec_bank_5        "                                              "
quietly label variable          subjsuper_ba~_5        "                                              "
quietly label variable          subjind_bkrpt_5        "                                              "
quietly label variable          subjspec_bkr~_5        "                                              "
quietly label variable          subjsuper_bk~_5        "                                              "
quietly label variable          subjind_civ_5          "                                              "
quietly label variable          subjspec_civ_5         "                                              "
quietly label variable          subjsuper_civ_5        "                                              "
quietly label variable          subjind_comm_5         "                                              "
quietly label variable          subjspec_comm_5        "                                              "
quietly label variable          subjsuper_co~_5        "                                              "
quietly label variable          subjind_cmerc_5        "                                              "
quietly label variable          subjspec_cme~_5        "                                              "
quietly label variable          subjsuper_cm~_5        "                                              "
quietly label variable          subjind_crim_5         "                                              "
quietly label variable          subjspec_crim_5        "                                              "
quietly label variable          subjsuper_cr~_5        "                                              "
quietly label variable          subjind_dom_5          "                                              "
quietly label variable          subjspec_dom_5         "                                              "
quietly label variable          subjsuper_dom_5        "                                              "
quietly label variable          subjind_emp_5          "                                              "
quietly label variable          subjspec_emp_5         "                                              "
quietly label variable          subjsuper_emp_5        "                                              "
quietly label variable          subjind_ene_5          "                                              "
quietly label variable          subjspec_ene_5         "                                              "
quietly label variable          subjsuper_ene_5        "                                              "
quietly label variable          subjind_env_5          "                                              "
quietly label variable          subjspec_env_5         "                                              "
quietly label variable          subjsuper_env_5        "                                              "
quietly label variable          subjind_est_5          "                                              "
quietly label variable          subjspec_est_5         "                                              "
quietly label variable          subjsuper_est_5        "                                              "
quietly label variable          subjind_govt_5         "                                              "
quietly label variable          subjspec_govt_5        "                                              "
quietly label variable          subjsuper_go~_5        "                                              "
quietly label variable          subjind_imm_5          "                                              "
quietly label variable          subjspec_imm_5         "                                              "
quietly label variable          subjsuper_imm_5        "                                              "
quietly label variable          subjind_tax_5          "                                              "
quietly label variable          subjspec_tax_5         "                                              "
quietly label variable          subjsuper_tax_5        "                                              "
quietly label variable          subjind_ins_5          "                                              "
quietly label variable          subjspec_ins_5         "                                              "
quietly label variable          subjsuper_ins_5        "                                              "
quietly label variable          subjind_int_5          "                                              "
quietly label variable          subjspec_int_5         "                                              "
quietly label variable          subjsuper_int_5        "                                              "
quietly label variable          subjind_lab_5          "                                              "
quietly label variable          subjspec_lab_5         "                                              "
quietly label variable          subjsuper_lab_5        "                                              "
quietly label variable          subjind_pat_5          "                                              "
quietly label variable          subjspec_pat_5         "                                              "
quietly label variable          subjsuper_pat_5        "                                              "
quietly label variable          subjind_real_5         "                                              "
quietly label variable          subjspec_real_5        "                                              "
quietly label variable          subjsuper_re~_5        "                                              "
quietly label variable          subjind_sec_5          "                                              "
quietly label variable          subjspec_sec_5         "                                              "
quietly label variable          subjsuper_sec_5        "                                              "
quietly label variable          subjind_tort_5         "                                              "
quietly label variable          subjspec_tort_5        "                                              "
quietly label variable          subjsuper_to~_5        "                                              "
quietly label variable          subjind_other_5        "                                              "
quietly label variable          subjspec_oth~_5        "                                              "
quietly label variable          subjsuper_ot~_5        "                                              "
quietly label variable          herf_subj_5            "Herfindahl index for dispersion of time       "
quietly label variable          subj_adm_15            "Subject: admin law                            "
quietly label variable          subj_anti_15           "Subject: antitrust                            "
quietly label variable          subj_bank_15           "Subject: banking                              "
quietly label variable          subj_bkrpt_15          "subject: bankruptcy                           "
quietly label variable          subj_civ_15            "subject: civil rights                         "
quietly label variable          subj_comm_15           "subjects: communication                       "
quietly label variable          subj_cmerc_15          "subject: commercial                           "
quietly label variable          subj_crim_15           "subject: criminal                             "
quietly label variable          subj_dom_15            "subject: domestic rl                          "
quietly label variable          subj_emp_15            "subject: employeeben                          "
quietly label variable          subj_ene_15            "subject: engergy                              "
quietly label variable          subj_env_15            "subject: environment                          "
quietly label variable          subj_est_15            "subject: estate plan                          "
quietly label variable          subj_govt_15           "subject: govt contractor                      "
quietly label variable          subj_imm_15            "subject: immigration                          "
quietly label variable          subj_tax_15            "subject: income tax                           "
quietly label variable          subj_ins_15            "subject insurance                             "
quietly label variable          subj_int_15            "subject: international                        "
quietly label variable          subj_lab_15            "subject: labor relations                      "
quietly label variable          subj_pat_15            "subject: patent/trademark                     "
quietly label variable          subj_real_15           "subject: real property                        "
quietly label variable          subj_sec_15            "subject: securities                           "
quietly label variable          subj_tort_15           "subject: tort                                 "
quietly label variable          subj_other_15          "subject: other                                "
quietly label variable          missingsubj_15         "                                              "
quietly label variable          subjind_adm_15         "spend more than 10% of time on it             "
quietly label variable          subjspec_adm_15        "spend more than 25% of time on it             "
quietly label variable          subjsuper_ad~15        "spend more than 50% of time on it             "
quietly label variable          subjind_anti_15        "                                              "
quietly label variable          subjspec_ant~15        "                                              "
quietly label variable          subjsuper_an~15        "                                              "
quietly label variable          subjind_bank_15        "                                              "
quietly label variable          subjspec_ban~15        "                                              "
quietly label variable          subjsuper_ba~15        "                                              "
quietly label variable          subjind_bkrp~15        "                                              "
quietly label variable          subjspec_bkr~15        "                                              "
quietly label variable          subjsuper_bk~15        "                                              "
quietly label variable          subjind_civ_15         "                                              "
quietly label variable          subjspec_civ_15        "                                              "
quietly label variable          subjsuper_ci~15        "                                              "
quietly label variable          subjind_comm_15        "                                              "
quietly label variable          subjspec_com~15        "                                              "
quietly label variable          subjsuper_co~15        "                                              "
quietly label variable          subjind_cmer~15        "                                              "
quietly label variable          subjspec_cme~15        "                                              "
quietly label variable          subjsuper_cm~15        "                                              "
quietly label variable          subjind_crim_15        "                                              "
quietly label variable          subjspec_cri~15        "                                              "
quietly label variable          subjsuper_cr~15        "                                              "
quietly label variable          subjind_dom_15         "                                              "
quietly label variable          subjspec_dom_15        "                                              "
quietly label variable          subjsuper_do~15        "                                              "
quietly label variable          subjind_emp_15         "                                              "
quietly label variable          subjspec_emp_15        "                                              "
quietly label variable          subjsuper_em~15        "                                              "
quietly label variable          subjind_ene_15         "                                              "
quietly label variable          subjspec_ene_15        "                                              "
quietly label variable          subjsuper_~e_15        "                                              "
quietly label variable          subjind_env_15         "                                              "
quietly label variable          subjspec_env_15        "                                              "
quietly label variable          subjsuper~nv_15        "                                              "
quietly label variable          subjind_est_15         "                                              "
quietly label variable          subjspec_est_15        "                                              "
quietly label variable          subjsuper_es~15        "                                              "
quietly label variable          subjind_govt_15        "                                              "
quietly label variable          subjspec_gov~15        "                                              "
quietly label variable          subjsuper_go~15        "                                              "
quietly label variable          subjind_imm_15         "                                              "
quietly label variable          subjspec_imm_15        "                                              "
quietly label variable          subjsuper_im~15        "                                              "
quietly label variable          subjind_tax_15         "                                              "
quietly label variable          subjspec_tax_15        "                                              "
quietly label variable          subjsuper_ta~15        "                                              "
quietly label variable          subjind_ins_15         "                                              "
quietly label variable          subjspec_ins_15        "                                              "
quietly label variable          subjsuper_~s_15        "                                              "
quietly label variable          subjind_int_15         "                                              "
quietly label variable          subjspec_int_15        "                                              "
quietly label variable          subjsuper~nt_15        "                                              "
quietly label variable          subjind_lab_15         "                                              "
quietly label variable          subjspec_lab_15        "                                              "
quietly label variable          subjsuper_la~15        "                                              "
quietly label variable          subjind_pat_15         "                                              "
quietly label variable          subjspec_pat_15        "                                              "
quietly label variable          subjsuper_pa~15        "                                              "
quietly label variable          subjind_real_15        "                                              "
quietly label variable          subjspec_rea~15        "                                              "
quietly label variable          subjsuper_re~15        "                                              "
quietly label variable          subjind_sec_15         "                                              "
quietly label variable          subjspec_sec_15        "                                              "
quietly label variable          subjsuper_se~15        "                                              "
quietly label variable          subjind_tort_15        "                                              "
quietly label variable          subjspec_tor~15        "                                              "
quietly label variable          subjsuper_to~15        "                                              "
quietly label variable          subjind_othe~15        "                                              "
quietly label variable          subjspec_oth~15        "                                              "
quietly label variable          subjsuper_ot~15        "                                              "
quietly label variable          herf_subj_15           "Herfindahl index for dispersion of time       "
quietly label variable          subj_adm_25            "Subject: admin law                            "
quietly label variable          subj_anti_25           "Subject: antitrust                            "
quietly label variable          subj_bank_25           "Subject: banking                              "
quietly label variable          subj_bkrpt_25          "subject: bankruptcy                           "
quietly label variable          subj_civ_25            "subject: civil rights                         "
quietly label variable          subj_comm_25           "subjects: communication                       "
quietly label variable          subj_cmerc_25          "subject: commercial                           "
quietly label variable          subj_crim_25           "subject: criminal                             "
quietly label variable          subj_dom_25            "subject: domestic rl                          "
quietly label variable          subj_emp_25            "subject: employeeben                          "
quietly label variable          subj_ene_25            "subject: engergy                              "
quietly label variable          subj_env_25            "subject: environment                          "
quietly label variable          subj_est_25            "subject: estate plan                          "
quietly label variable          subj_govt_25           "subject: govt contractor                      "
quietly label variable          subj_imm_25            "subject: immigration                          "
quietly label variable          subj_tax_25            "subject: income tax                           "
quietly label variable          subj_ins_25            "subject insurance                             "
quietly label variable          subj_int_25            "subject: international                        "
quietly label variable          subj_lab_25            "subject: labor relations                      "
quietly label variable          subj_pat_25            "subject: patent/trademark                     "
quietly label variable          subj_real_25           "subject: real property                        "
quietly label variable          subj_sec_25            "subject: securities                           "
quietly label variable          subj_tort_25           "subject: tort                                 "
quietly label variable          subj_other_25          "subject: other                                "
quietly label variable          missingsubj_25         "                                              "
quietly label variable          subjind_adm_25         "spend more than 10% of time on it             "
quietly label variable          subjspec_adm_25        "spend more than 25% of time on it             "
quietly label variable          subjsuper_ad~25        "spend more than 50% of time on it             "
quietly label variable          subjind_anti_25        "                                              "
quietly label variable          subjspec_ant~25        "                                              "
quietly label variable          subjsuper_an~25        "                                              "
quietly label variable          subjind_bank_25        "                                              "
quietly label variable          subjspec_ban~25        "                                              "
quietly label variable          subjsuper_ba~25        "                                              "
quietly label variable          subjind_bkrp~25        "                                              "
quietly label variable          subjspec_bkr~25        "                                              "
quietly label variable          subjsuper_bk~25        "                                              "
quietly label variable          subjind_civ_25         "                                              "
quietly label variable          subjspec_civ_25        "                                              "
quietly label variable          subjsuper_ci~25        "                                              "
quietly label variable          subjind_comm_25        "                                              "
quietly label variable          subjspec_com~25        "                                              "
quietly label variable          subjsuper_co~25        "                                              "
quietly label variable          subjind_cmer~25        "                                              "
quietly label variable          subjspec_cme~25        "                                              "
quietly label variable          subjsuper_cm~25        "                                              "
quietly label variable          subjind_crim_25        "                                              "
quietly label variable          subjspec_cri~25        "                                              "
quietly label variable          subjsuper_cr~25        "                                              "
quietly label variable          subjind_dom_25         "                                              "
quietly label variable          subjspec_dom_25        "                                              "
quietly label variable          subjsuper_do~25        "                                              "
quietly label variable          subjind_emp_25         "                                              "
quietly label variable          subjspec_emp_25        "                                              "
quietly label variable          subjsuper_em~25        "                                              "
quietly label variable          subjind_ene_25         "                                              "
quietly label variable          subjspec_ene_25        "                                              "
quietly label variable          subjsuper_~e_25        "                                              "
quietly label variable          subjind_env_25         "                                              "
quietly label variable          subjspec_env_25        "                                              "
quietly label variable          subjsuper~nv_25        "                                              "
quietly label variable          subjind_est_25         "                                              "
quietly label variable          subjspec_est_25        "                                              "
quietly label variable          subjsuper_es~25        "                                              "
quietly label variable          subjind_govt_25        "                                              "
quietly label variable          subjspec_gov~25        "                                              "
quietly label variable          subjsuper_go~25        "                                              "
quietly label variable          subjind_imm_25         "                                              "
quietly label variable          subjspec_imm_25        "                                              "
quietly label variable          subjsuper_im~25        "                                              "
quietly label variable          subjind_tax_25         "                                              "
quietly label variable          subjspec_tax_25        "                                              "
quietly label variable          subjsuper_ta~25        "                                              "
quietly label variable          subjind_ins_25         "                                              "
quietly label variable          subjspec_ins_25        "                                              "
quietly label variable          subjsuper_~s_25        "                                              "
quietly label variable          subjind_int_25         "                                              "
quietly label variable          subjspec_int_25        "                                              "
quietly label variable          subjsuper~nt_25        "                                              "
quietly label variable          subjind_lab_25         "                                              "
quietly label variable          subjspec_lab_25        "                                              "
quietly label variable          subjsuper_la~25        "                                              "
quietly label variable          subjind_pat_25         "                                              "
quietly label variable          subjspec_pat_25        "                                              "
quietly label variable          subjsuper_pa~25        "                                              "
quietly label variable          subjind_real_25        "                                              "
quietly label variable          subjspec_rea~25        "                                              "
quietly label variable          subjsuper_re~25        "                                              "
quietly label variable          subjind_sec_25         "                                              "
quietly label variable          subjspec_sec_25        "                                              "
quietly label variable          subjsuper_se~25        "                                              "
quietly label variable          subjind_tort_25        "                                              "
quietly label variable          subjspec_tor~25        "                                              "
quietly label variable          subjsuper_to~25        "                                              "
quietly label variable          subjind_othe~25        "                                              "
quietly label variable          subjspec_oth~25        "                                              "
quietly label variable          subjsuper_ot~25        "                                              "
quietly label variable          herf_subj_25           "Herfindahl index for dispersion of time       "
quietly label variable          client_rich_5          "client: rich individuals                      "
quietly label variable          client_othind_5        "client: other individuals                     "
quietly label variable          client_smbus_5         "client: small business                        "
quietly label variable          client_mdlg_5          "client: med-legal business                    "
quietly label variable          client_f500_5          "client: fortune 500                           "
quietly label variable          client_gov_5           "client: government                            "
quietly label variable          client_nonp_5          "client: non profit                            "
quietly label variable          client_oth_5           "client: other                                 "
quietly label variable          missingclient_5        "                                              "
quietly label variable          clientind_ri~_5        "Spend more than 10% of time with these clients"
quietly label variable          clientspec_r~_5        "Spend more than 25% of time with these clients"
quietly label variable          clientsupe~ch_5        "Spend more than 50% of time with these clients"
quietly label variable          clientind_o~d_5        "                                              "
quietly label variable          clientspec_~d_5        "                                              "
quietly label variable          clientsuper~d_5        "                                              "
quietly label variable          clientind_sm~_5        "                                              "
quietly label variable          clientspec_s~_5        "                                              "
quietly label variable          clientsuper~s_5        "                                              "
quietly label variable          clientind_f5~_5        "                                              "
quietly label variable          clientspec_f~_5        "                                              "
quietly label variable          clientsuper~0_5        "                                              "
quietly label variable          clientind_md~_5        "                                              "
quietly label variable          clientspec_m~_5        "                                              "
quietly label variable          clientsuper~g_5        "                                              "
quietly label variable          clientind_gov_5        "                                              "
quietly label variable          clientspec_g~_5        "                                              "
quietly label variable          clientsuper~v_5        "                                              "
quietly label variable          clientind_no~_5        "                                              "
quietly label variable          clientspec_n~_5        "                                              "
quietly label variable          clientsuper~p_5        "                                              "
quietly label variable          clientind_oth_5        "                                              "
quietly label variable          clientspec~th_5        "                                              "
quietly label variable          clientsupe~th_5        "                                              "
quietly label variable          herf_client_5          "                                              "
quietly label variable          client_rich_15         "client: rich individuals                      "
quietly label variable          client_othin~15        "client: other individuals                     "
quietly label variable          client_smbus_15        "client: small business                        "
quietly label variable          client_mdlg_15         "client: med-legal business                    "
quietly label variable          client_f500_15         "client: fortune 500                           "
quietly label variable          client_gov_15          "client: government                            "
quietly label variable          client_nonp_15         "client: non profit                            "
quietly label variable          client_oth_15          "client: other                                 "
quietly label variable          missingclien~15        "                                              "
quietly label variable          clientind_ri~15        "Spend more than 10% of time with these clients"
quietly label variable          clientspec_r~15        "Spend more than 25% of time with these clients"
quietly label variable          clientsup~ch_15        "Spend more than 50% of time with these clients"
quietly label variable          clientind_~d_15        "                                              "
quietly label variable          clientspec~d_15        "                                              "
quietly label variable          clientsupe~d_15        "                                              "
quietly label variable          clientind_sm~15        "                                              "
quietly label variable          clientspec_s~15        "                                              "
quietly label variable          clientsupe~s_15        "                                              "
quietly label variable          clientind_f5~15        "                                              "
quietly label variable          clientspec_f~15        "                                              "
quietly label variable          clientsupe~0_15        "                                              "
quietly label variable          clientind_md~15        "                                              "
quietly label variable          clientspec_m~15        "                                              "
quietly label variable          clientsupe~g_15        "                                              "
quietly label variable          clientind_go~15        "                                              "
quietly label variable          clientspec_g~15        "                                              "
quietly label variable          clientsupe~v_15        "                                              "
quietly label variable          clientind_no~15        "                                              "
quietly label variable          clientspec_n~15        "                                              "
quietly label variable          clientsupe~p_15        "                                              "
quietly label variable          clientind~th_15        "                                              "
quietly label variable          clientspe~th_15        "                                              "
quietly label variable          clientsup~th_15        "                                              "
quietly label variable          herf_client_15         "                                              "
quietly label variable          client_rich_25         "client: rich individuals                      "
quietly label variable          client_othin~25        "client: other individuals                     "
quietly label variable          client_smbus_25        "client: small business                        "
quietly label variable          client_mdlg_25         "client: med-legal business                    "
quietly label variable          client_f500_25         "client: fortune 500                           "
quietly label variable          client_gov_25          "client: government                            "
quietly label variable          client_nonp_25         "client: non profit                            "
quietly label variable          client_oth_25          "client: other                                 "
quietly label variable          missingclien~25        "                                              "
quietly label variable          clientind_ri~25        "Spend more than 10% of time with these clients"
quietly label variable          clientspec_r~25        "Spend more than 25% of time with these clients"
quietly label variable          clientsup~ch_25        "Spend more than 50% of time with these clients"
quietly label variable          clientind_~d_25        "                                              "
quietly label variable          clientspec~d_25        "                                              "
quietly label variable          clientsupe~d_25        "                                              "
quietly label variable          clientind_sm~25        "                                              "
quietly label variable          clientspec_s~25        "                                              "
quietly label variable          clientsupe~s_25        "                                              "
quietly label variable          clientind_f5~25        "                                              "
quietly label variable          clientspec_f~25        "                                              "
quietly label variable          clientsupe~0_25        "                                              "
quietly label variable          clientind_md~25        "                                              "
quietly label variable          clientspec_m~25        "                                              "
quietly label variable          clientsupe~g_25        "                                              "
quietly label variable          clientind_go~25        "                                              "
quietly label variable          clientspec_g~25        "                                              "
quietly label variable          clientsupe~v_25        "                                              "
quietly label variable          clientind_no~25        "                                              "
quietly label variable          clientspec_n~25        "                                              "
quietly label variable          clientsupe~p_25        "                                              "
quietly label variable          clientind~th_25        "                                              "
quietly label variable          clientspe~th_25        "                                              "
quietly label variable          clientsup~th_25        "                                              "
quietly label variable          herf_client_25         "                                              "
quietly label variable          satis_fam_5            "satisfaction w/ family life                   "
quietly label variable          satis_famcar_5         "satisfaction with professional/family balance "
quietly label variable          satis_ls_5             "satisfaction w/ law school                    "
quietly label variable          satis_stress_5         "satisfaction with work stress                 "
quietly label variable          satis_contwk_5         "satisfaction w/ control over work             "
quietly label variable          satis_socval_5         "satisfaction w/ social values                 "
quietly label variable          satis_relco_5          "satisfaction with rel coworkers               "
quietly label variable          satis_inc_5            "satisfaction with income                      "
quietly label variable          satis_prsocv_5         "satisfaction with problem solving             "
quietly label variable          satis_intel_5          "satisfaction with intellect                   "
quietly label variable          satis_prest_5          "satisfaction with prestige                    "
quietly label variable          satis_over_5           "satisfaction overall                          "
quietly label variable          satis_fam_15           "satisfaction w/ family life                   "
quietly label variable          satis_famcar_15        "satisfaction with professional/family balance "
quietly label variable          satis_ls_15            "satisfaction w/ law school                    "
quietly label variable          satis_stress_15        "satisfaction with work stress                 "
quietly label variable          satis_contwk_15        "satisfaction w/ control over work             "
quietly label variable          satis_socval_15        "satisfaction w/ social values                 "
quietly label variable          satis_relco_15         "satisfaction with rel coworkers               "
quietly label variable          satis_inc_15           "satisfaction with income                      "
quietly label variable          satis_prsocv_15        "satisfaction with problem solving             "
quietly label variable          satis_intel_15         "satisfaction with intellect                   "
quietly label variable          satis_prest_15         "satisfaction with prestige                    "
quietly label variable          satis_over_15          "satisfaction overall                          "
quietly label variable          satis_fam_25           "satisfaction w/ family life                   "
quietly label variable          satis_famcar_25        "satisfaction with professional/family balance "
quietly label variable          satis_ls_25            "satisfaction w/ law school                    "
quietly label variable          satis_stress_25        "satisfaction with work stress                 "
quietly label variable          satis_contwk_25        "satisfaction w/ control over work             "
quietly label variable          satis_socval_25        "satisfaction w/ social values                 "
quietly label variable          satis_relco_25         "satisfaction with rel coworkers               "
quietly label variable          satis_inc_25           "satisfaction with income                      "
quietly label variable          satis_prsocv_25        "satisfaction with problem solving             "
quietly label variable          satis_intel_25         "satisfaction with intellect                   "
quietly label variable          satis_prest_25         "satisfaction with prestige                    "
quietly label variable          satis_over_25          "satisfaction overall                          "
quietly label variable          discrim_firm_5         "sex discrimination: firm                      "
quietly label variable          discrim_lawy~_5        "sex discrimination: other lawyers             "
quietly label variable          discrim_clie~_5        "sex discrimination: clients                   "
quietly label variable          discrim_firm_15        "sex discrimination: firm                      "
quietly label variable          discrim_lawy~15        "sex discrimination: other lawyers             "
quietly label variable          discrim_clie~15        "sex discrimination: clients                   "
quietly label variable          discrim_firm_25        "sex discrimination: firm                      "
quietly label variable          discrim_lawy~25        "sex discrimination: other lawyers             "
quietly label variable          discrim_clie~25        "sex discrimination: clients                   "
quietly label variable          rhat_5                 "Pr(returned_5)                                "
quietly label variable          weight_5               "weight for year 5                             "
quietly label variable          rhat_15                "Pr(returned_15)                               "
quietly label variable          weight_15              "weight for year 15                            "
